services:
  minio-server:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z 
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - minio.env
    command: server /data --console-address ":9001"
    volumes:
      - "./minio/data:/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - zookeeper
      - kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.5 
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.7.5
    ports:
      - 9092:9092
      - 29092:29092
    env_file: kafka.env
    depends_on:
      - zookeeper
networks:
  gallery_net:
    driver: bridge


