services:
  minio-server:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z 
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - minio.env
    command: server /data --console-address ":9001"
    volumes:
      - "./minio/data:/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - zookeeper
      - kafka
  # Pull the service but the code does not connect to it yet
  bucket-server:
    image: rustfs/rustfs:1.0.0-alpha.65
    container_name: bucket_storage 
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    env_file:
      - bucket.env
    volumes:
    - "./rustfs/data:/data"
    - "./rustfs/logs:/var/logs/rustfs/"
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - zookeeper
      - kafka
    networks:
      - gallery_net
  db:
    # Note!: Change this for x64 cpus from `arm64` to `amd64`
    image: timescale/timescaledb-ha:pg17-arm64
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gallery_net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.5 
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - gallery_net
  kafka:
    image: confluentinc/cp-kafka:7.7.5
    ports:
      - 9092:9092
      - 29092:29092
    env_file: kafka.env
    depends_on:
      - zookeeper
    networks:
      - gallery_net
networks:
  gallery_net:
    name: gallery_net
    driver: bridge


