// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: gallery_view.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "gallery_view";

export interface UploadImageRequest {
  filename: string;
  filesize: number;
  filehash: string;
}

export interface SignedLinkResponse {
  bucketLink: string;
}

export interface EmptyRequest {
}

export interface FilterGalleryRequest {
  page?: string | undefined;
  size?: string | undefined;
  searchText?: string | undefined;
  theme?: string | undefined;
  ratio?: string | undefined;
}

export interface GalleryImagesResponse {
  images: GalleryImage[];
  count: number;
}

export interface GalleryImage {
  imgUrl: string;
  ariaText: string;
  aspect: string;
  theme: string;
  altText: string;
}

export interface FilterOptionResponse {
  aspects: string[];
  themes: string[];
}

function createBaseUploadImageRequest(): UploadImageRequest {
  return { filename: "", filesize: 0, filehash: "" };
}

export const UploadImageRequest: MessageFns<UploadImageRequest> = {
  encode(message: UploadImageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== "") {
      writer.uint32(10).string(message.filename);
    }
    if (message.filesize !== 0) {
      writer.uint32(16).int32(message.filesize);
    }
    if (message.filehash !== "") {
      writer.uint32(26).string(message.filehash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadImageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadImageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.filesize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filehash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadImageRequest {
    return {
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      filesize: isSet(object.filesize) ? globalThis.Number(object.filesize) : 0,
      filehash: isSet(object.filehash) ? globalThis.String(object.filehash) : "",
    };
  },

  toJSON(message: UploadImageRequest): unknown {
    const obj: any = {};
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.filesize !== 0) {
      obj.filesize = Math.round(message.filesize);
    }
    if (message.filehash !== "") {
      obj.filehash = message.filehash;
    }
    return obj;
  },

  create(base?: DeepPartial<UploadImageRequest>): UploadImageRequest {
    return UploadImageRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UploadImageRequest>): UploadImageRequest {
    const message = createBaseUploadImageRequest();
    message.filename = object.filename ?? "";
    message.filesize = object.filesize ?? 0;
    message.filehash = object.filehash ?? "";
    return message;
  },
};

function createBaseSignedLinkResponse(): SignedLinkResponse {
  return { bucketLink: "" };
}

export const SignedLinkResponse: MessageFns<SignedLinkResponse> = {
  encode(message: SignedLinkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bucketLink !== "") {
      writer.uint32(10).string(message.bucketLink);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignedLinkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignedLinkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bucketLink = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignedLinkResponse {
    return { bucketLink: isSet(object.bucketLink) ? globalThis.String(object.bucketLink) : "" };
  },

  toJSON(message: SignedLinkResponse): unknown {
    const obj: any = {};
    if (message.bucketLink !== "") {
      obj.bucketLink = message.bucketLink;
    }
    return obj;
  },

  create(base?: DeepPartial<SignedLinkResponse>): SignedLinkResponse {
    return SignedLinkResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignedLinkResponse>): SignedLinkResponse {
    const message = createBaseSignedLinkResponse();
    message.bucketLink = object.bucketLink ?? "";
    return message;
  },
};

function createBaseEmptyRequest(): EmptyRequest {
  return {};
}

export const EmptyRequest: MessageFns<EmptyRequest> = {
  encode(_: EmptyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyRequest {
    return {};
  },

  toJSON(_: EmptyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<EmptyRequest>): EmptyRequest {
    return EmptyRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<EmptyRequest>): EmptyRequest {
    const message = createBaseEmptyRequest();
    return message;
  },
};

function createBaseFilterGalleryRequest(): FilterGalleryRequest {
  return { page: undefined, size: undefined, searchText: undefined, theme: undefined, ratio: undefined };
}

export const FilterGalleryRequest: MessageFns<FilterGalleryRequest> = {
  encode(message: FilterGalleryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      writer.uint32(10).string(message.page);
    }
    if (message.size !== undefined) {
      writer.uint32(18).string(message.size);
    }
    if (message.searchText !== undefined) {
      writer.uint32(26).string(message.searchText);
    }
    if (message.theme !== undefined) {
      writer.uint32(34).string(message.theme);
    }
    if (message.ratio !== undefined) {
      writer.uint32(42).string(message.ratio);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FilterGalleryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilterGalleryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.page = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.size = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.searchText = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.theme = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ratio = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FilterGalleryRequest {
    return {
      page: isSet(object.page) ? globalThis.String(object.page) : undefined,
      size: isSet(object.size) ? globalThis.String(object.size) : undefined,
      searchText: isSet(object.searchText) ? globalThis.String(object.searchText) : undefined,
      theme: isSet(object.theme) ? globalThis.String(object.theme) : undefined,
      ratio: isSet(object.ratio) ? globalThis.String(object.ratio) : undefined,
    };
  },

  toJSON(message: FilterGalleryRequest): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = message.page;
    }
    if (message.size !== undefined) {
      obj.size = message.size;
    }
    if (message.searchText !== undefined) {
      obj.searchText = message.searchText;
    }
    if (message.theme !== undefined) {
      obj.theme = message.theme;
    }
    if (message.ratio !== undefined) {
      obj.ratio = message.ratio;
    }
    return obj;
  },

  create(base?: DeepPartial<FilterGalleryRequest>): FilterGalleryRequest {
    return FilterGalleryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FilterGalleryRequest>): FilterGalleryRequest {
    const message = createBaseFilterGalleryRequest();
    message.page = object.page ?? undefined;
    message.size = object.size ?? undefined;
    message.searchText = object.searchText ?? undefined;
    message.theme = object.theme ?? undefined;
    message.ratio = object.ratio ?? undefined;
    return message;
  },
};

function createBaseGalleryImagesResponse(): GalleryImagesResponse {
  return { images: [], count: 0 };
}

export const GalleryImagesResponse: MessageFns<GalleryImagesResponse> = {
  encode(message: GalleryImagesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.images) {
      GalleryImage.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.count !== 0) {
      writer.uint32(16).int32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GalleryImagesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGalleryImagesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.images.push(GalleryImage.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GalleryImagesResponse {
    return {
      images: globalThis.Array.isArray(object?.images) ? object.images.map((e: any) => GalleryImage.fromJSON(e)) : [],
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: GalleryImagesResponse): unknown {
    const obj: any = {};
    if (message.images?.length) {
      obj.images = message.images.map((e) => GalleryImage.toJSON(e));
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create(base?: DeepPartial<GalleryImagesResponse>): GalleryImagesResponse {
    return GalleryImagesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GalleryImagesResponse>): GalleryImagesResponse {
    const message = createBaseGalleryImagesResponse();
    message.images = object.images?.map((e) => GalleryImage.fromPartial(e)) || [];
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseGalleryImage(): GalleryImage {
  return { imgUrl: "", ariaText: "", aspect: "", theme: "", altText: "" };
}

export const GalleryImage: MessageFns<GalleryImage> = {
  encode(message: GalleryImage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.imgUrl !== "") {
      writer.uint32(10).string(message.imgUrl);
    }
    if (message.ariaText !== "") {
      writer.uint32(18).string(message.ariaText);
    }
    if (message.aspect !== "") {
      writer.uint32(26).string(message.aspect);
    }
    if (message.theme !== "") {
      writer.uint32(34).string(message.theme);
    }
    if (message.altText !== "") {
      writer.uint32(42).string(message.altText);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GalleryImage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGalleryImage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.imgUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ariaText = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.aspect = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.theme = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.altText = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GalleryImage {
    return {
      imgUrl: isSet(object.imgUrl) ? globalThis.String(object.imgUrl) : "",
      ariaText: isSet(object.ariaText) ? globalThis.String(object.ariaText) : "",
      aspect: isSet(object.aspect) ? globalThis.String(object.aspect) : "",
      theme: isSet(object.theme) ? globalThis.String(object.theme) : "",
      altText: isSet(object.altText) ? globalThis.String(object.altText) : "",
    };
  },

  toJSON(message: GalleryImage): unknown {
    const obj: any = {};
    if (message.imgUrl !== "") {
      obj.imgUrl = message.imgUrl;
    }
    if (message.ariaText !== "") {
      obj.ariaText = message.ariaText;
    }
    if (message.aspect !== "") {
      obj.aspect = message.aspect;
    }
    if (message.theme !== "") {
      obj.theme = message.theme;
    }
    if (message.altText !== "") {
      obj.altText = message.altText;
    }
    return obj;
  },

  create(base?: DeepPartial<GalleryImage>): GalleryImage {
    return GalleryImage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GalleryImage>): GalleryImage {
    const message = createBaseGalleryImage();
    message.imgUrl = object.imgUrl ?? "";
    message.ariaText = object.ariaText ?? "";
    message.aspect = object.aspect ?? "";
    message.theme = object.theme ?? "";
    message.altText = object.altText ?? "";
    return message;
  },
};

function createBaseFilterOptionResponse(): FilterOptionResponse {
  return { aspects: [], themes: [] };
}

export const FilterOptionResponse: MessageFns<FilterOptionResponse> = {
  encode(message: FilterOptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.aspects) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.themes) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FilterOptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilterOptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.aspects.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.themes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FilterOptionResponse {
    return {
      aspects: globalThis.Array.isArray(object?.aspects) ? object.aspects.map((e: any) => globalThis.String(e)) : [],
      themes: globalThis.Array.isArray(object?.themes) ? object.themes.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: FilterOptionResponse): unknown {
    const obj: any = {};
    if (message.aspects?.length) {
      obj.aspects = message.aspects;
    }
    if (message.themes?.length) {
      obj.themes = message.themes;
    }
    return obj;
  },

  create(base?: DeepPartial<FilterOptionResponse>): FilterOptionResponse {
    return FilterOptionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FilterOptionResponse>): FilterOptionResponse {
    const message = createBaseFilterOptionResponse();
    message.aspects = object.aspects?.map((e) => e) || [];
    message.themes = object.themes?.map((e) => e) || [];
    return message;
  },
};

export type GalleryViewDefinition = typeof GalleryViewDefinition;
export const GalleryViewDefinition = {
  name: "GalleryView",
  fullName: "gallery_view.GalleryView",
  methods: {
    uploadImage: {
      name: "UploadImage",
      requestType: UploadImageRequest,
      requestStream: false,
      responseType: SignedLinkResponse,
      responseStream: false,
      options: {},
    },
    listGallery: {
      name: "ListGallery",
      requestType: FilterGalleryRequest,
      requestStream: false,
      responseType: GalleryImagesResponse,
      responseStream: false,
      options: {},
    },
    filterOptions: {
      name: "FilterOptions",
      requestType: EmptyRequest,
      requestStream: false,
      responseType: FilterOptionResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface GalleryViewServiceImplementation<CallContextExt = {}> {
  uploadImage(
    request: UploadImageRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SignedLinkResponse>>;
  listGallery(
    request: FilterGalleryRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GalleryImagesResponse>>;
  filterOptions(
    request: EmptyRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<FilterOptionResponse>>;
}

export interface GalleryViewClient<CallOptionsExt = {}> {
  uploadImage(
    request: DeepPartial<UploadImageRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SignedLinkResponse>;
  listGallery(
    request: DeepPartial<FilterGalleryRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GalleryImagesResponse>;
  filterOptions(
    request: DeepPartial<EmptyRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<FilterOptionResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
