// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: user_auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "user_auth";

export interface EmptyRequest {
}

export interface EmptyResponse {
}

export interface ServerPublicKeys {
  publicKey: string;
}

export interface UserPublicAuth {
  ephemeralPublicKey: string;
  nonce: string;
  message: string;
}

export interface UserAuthResponse {
  status: string;
  bearer: string;
  expires: number;
}

function createBaseEmptyRequest(): EmptyRequest {
  return {};
}

export const EmptyRequest: MessageFns<EmptyRequest> = {
  encode(_: EmptyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyRequest {
    return {};
  },

  toJSON(_: EmptyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<EmptyRequest>): EmptyRequest {
    return EmptyRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<EmptyRequest>): EmptyRequest {
    const message = createBaseEmptyRequest();
    return message;
  },
};

function createBaseEmptyResponse(): EmptyResponse {
  return {};
}

export const EmptyResponse: MessageFns<EmptyResponse> = {
  encode(_: EmptyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyResponse {
    return {};
  },

  toJSON(_: EmptyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<EmptyResponse>): EmptyResponse {
    return EmptyResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<EmptyResponse>): EmptyResponse {
    const message = createBaseEmptyResponse();
    return message;
  },
};

function createBaseServerPublicKeys(): ServerPublicKeys {
  return { publicKey: "" };
}

export const ServerPublicKeys: MessageFns<ServerPublicKeys> = {
  encode(message: ServerPublicKeys, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publicKey !== "") {
      writer.uint32(10).string(message.publicKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerPublicKeys {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerPublicKeys();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publicKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerPublicKeys {
    return { publicKey: isSet(object.publicKey) ? globalThis.String(object.publicKey) : "" };
  },

  toJSON(message: ServerPublicKeys): unknown {
    const obj: any = {};
    if (message.publicKey !== "") {
      obj.publicKey = message.publicKey;
    }
    return obj;
  },

  create(base?: DeepPartial<ServerPublicKeys>): ServerPublicKeys {
    return ServerPublicKeys.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ServerPublicKeys>): ServerPublicKeys {
    const message = createBaseServerPublicKeys();
    message.publicKey = object.publicKey ?? "";
    return message;
  },
};

function createBaseUserPublicAuth(): UserPublicAuth {
  return { ephemeralPublicKey: "", nonce: "", message: "" };
}

export const UserPublicAuth: MessageFns<UserPublicAuth> = {
  encode(message: UserPublicAuth, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ephemeralPublicKey !== "") {
      writer.uint32(10).string(message.ephemeralPublicKey);
    }
    if (message.nonce !== "") {
      writer.uint32(18).string(message.nonce);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserPublicAuth {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserPublicAuth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ephemeralPublicKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nonce = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserPublicAuth {
    return {
      ephemeralPublicKey: isSet(object.ephemeralPublicKey) ? globalThis.String(object.ephemeralPublicKey) : "",
      nonce: isSet(object.nonce) ? globalThis.String(object.nonce) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: UserPublicAuth): unknown {
    const obj: any = {};
    if (message.ephemeralPublicKey !== "") {
      obj.ephemeralPublicKey = message.ephemeralPublicKey;
    }
    if (message.nonce !== "") {
      obj.nonce = message.nonce;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create(base?: DeepPartial<UserPublicAuth>): UserPublicAuth {
    return UserPublicAuth.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserPublicAuth>): UserPublicAuth {
    const message = createBaseUserPublicAuth();
    message.ephemeralPublicKey = object.ephemeralPublicKey ?? "";
    message.nonce = object.nonce ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseUserAuthResponse(): UserAuthResponse {
  return { status: "", bearer: "", expires: 0 };
}

export const UserAuthResponse: MessageFns<UserAuthResponse> = {
  encode(message: UserAuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.bearer !== "") {
      writer.uint32(18).string(message.bearer);
    }
    if (message.expires !== 0) {
      writer.uint32(24).uint64(message.expires);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserAuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bearer = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expires = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAuthResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      bearer: isSet(object.bearer) ? globalThis.String(object.bearer) : "",
      expires: isSet(object.expires) ? globalThis.Number(object.expires) : 0,
    };
  },

  toJSON(message: UserAuthResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.bearer !== "") {
      obj.bearer = message.bearer;
    }
    if (message.expires !== 0) {
      obj.expires = Math.round(message.expires);
    }
    return obj;
  },

  create(base?: DeepPartial<UserAuthResponse>): UserAuthResponse {
    return UserAuthResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserAuthResponse>): UserAuthResponse {
    const message = createBaseUserAuthResponse();
    message.status = object.status ?? "";
    message.bearer = object.bearer ?? "";
    message.expires = object.expires ?? 0;
    return message;
  },
};

export type AuthGreeterDefinition = typeof AuthGreeterDefinition;
export const AuthGreeterDefinition = {
  name: "AuthGreeter",
  fullName: "user_auth.AuthGreeter",
  methods: {
    /** Starts the cipher handshake process by returning public keys */
    greetAuth: {
      name: "GreetAuth",
      requestType: EmptyRequest,
      requestStream: false,
      responseType: ServerPublicKeys,
      responseStream: false,
      options: {},
    },
    exchangeAuth: {
      name: "ExchangeAuth",
      requestType: UserPublicAuth,
      requestStream: false,
      responseType: UserAuthResponse,
      responseStream: false,
      options: {},
    },
    logout: {
      name: "Logout",
      requestType: EmptyRequest,
      requestStream: false,
      responseType: EmptyResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface AuthGreeterServiceImplementation<CallContextExt = {}> {
  /** Starts the cipher handshake process by returning public keys */
  greetAuth(request: EmptyRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ServerPublicKeys>>;
  exchangeAuth(request: UserPublicAuth, context: CallContext & CallContextExt): Promise<DeepPartial<UserAuthResponse>>;
  logout(request: EmptyRequest, context: CallContext & CallContextExt): Promise<DeepPartial<EmptyResponse>>;
}

export interface AuthGreeterClient<CallOptionsExt = {}> {
  /** Starts the cipher handshake process by returning public keys */
  greetAuth(request: DeepPartial<EmptyRequest>, options?: CallOptions & CallOptionsExt): Promise<ServerPublicKeys>;
  exchangeAuth(request: DeepPartial<UserPublicAuth>, options?: CallOptions & CallOptionsExt): Promise<UserAuthResponse>;
  logout(request: DeepPartial<EmptyRequest>, options?: CallOptions & CallOptionsExt): Promise<EmptyResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
